replicaCount: 1

image:
  repository: ufocultist/smotrish
  tag: latest

env:
  DB_HOST: "%"
  DB_NAME: "smotrish_db"
  DB_USERNAME: "smotrish_user"
  DB_PASSWORD: ""

pvc:
  name: flask-pvc
  size: 1Gi

service:
  name: flask
  type: ClusterIP
  port: 8080
  targetPort: 8080