apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
  labels:
    app: {{ include "nginx.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
      listen 80;
      location / {
        include uwsgi_params;
        uwsgi_pass flask:8080;
      }
    }